# Generated by Django 5.1.1 on 2024-09-17 15:32

from django.db import migrations


def create_roles(apps, schema_editor):
    Role = apps.get_model("users", "Role")
    roles = ["member", "subscriber", "staff", "admin"]
    for role_name in roles:
        Role.objects.get_or_create(name=role_name)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_role_customuser_roles"),
    ]

    operations = [
        migrations.RunPython(create_roles),
    ]
