# Generated by Django 5.1.1 on 2024-09-28 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("order", models.PositiveIntegerField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/grades/"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/grades/"
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=2, null=True)),
                ("xp_threshold", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Rank",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/ranks/"),
                ),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="images/ranks/"),
                ),
                ("icon", models.CharField(blank=True, max_length=2, null=True)),
                ("order", models.PositiveIntegerField()),
                ("challenge_threshold", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/levels/"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/levels/"
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=2, null=True)),
                ("order", models.PositiveIntegerField()),
                ("pages_required", models.TextField(default="[]")),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.track"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaxAttainable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_questions", models.IntegerField(default=0)),
                ("total_pages", models.IntegerField(default=0)),
                ("total_challenges", models.IntegerField(default=0)),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.track"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                ("health", models.IntegerField(default=100)),
                ("questions_completed", models.TextField(default="[]")),
                ("pages_completed", models.TextField(default="[]")),
                ("challenges_completed", models.TextField(default="[]")),
                ("current_page", models.PositiveIntegerField(blank=True, null=True)),
                ("last_completed", models.DateTimeField(auto_now=True)),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.track"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
