# Generated by Django 5.1.1 on 2024-09-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="level",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rank",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
