# Generated by Django 5.1.1 on 2024-10-25 18:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_difficultylevel_track_order_course_module_section_and_more"),
        ("gameplay", "0002_grade_description_level_description_rank_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maxattainable",
            options={
                "verbose_name": "Max Attainable Value",
                "verbose_name_plural": "Max Attainable Values",
            },
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="current_page",
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="last_completed",
        ),
        migrations.AddField(
            model_name="userprogress",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprogress",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="challenges_completed",
            field=models.TextField(blank=True, default="[]"),
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="pages_completed",
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="questions_completed",
            field=models.TextField(blank=True, default="[]"),
        ),
        migrations.CreateModel(
            name="PagesCompleted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_id", models.PositiveIntegerField()),
                (
                    "completed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.track"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "track", "page_id")},
            },
        ),
        migrations.AddField(
            model_name="userprogress",
            name="pages_completed",
            field=models.ManyToManyField(blank=True, to="gameplay.pagescompleted"),
        ),
    ]
