# Generated by Django 5.1.1 on 2024-10-26 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0003_alter_maxattainable_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprogress",
            old_name="points",
            new_name="score",
        ),
    ]
